### ISSUE TITLE
Question: Consider Merging Projects

### ISSUE THREAD

**Issue by jkdba** [chritea/PSKeePass#1]
Hi I just found your project, I have also been working on a PowerShell KeePass module with the same basic intentions. 

I noticed some strengths in your code versus mine and vice-versa. Potentially we could consider working on the same project and bring the best of both worlds together.

Check out my project [here](https://github.com/jkdba/PowerKeePass) and let me know.

**Comment by chritea** [comment]
Hey,
I´ll look into your project and let you know but in general nothing speaks against it.
Christian

**Comment by jkdba** [comment]
Alright cool, look forward to hearing from you.

Thanks,
John

**Comment by jkdba** [comment]
Christian and I spoke we will merge projects on this repository, as it has already been advertised.
